## Homework 1

### Тема: настройка рабочей среды, работа с Git, структура репозитория и базовые операции в NumPy

### Испорт библиотеки

In [43]:
import numpy as np

### Создание массивов

In [44]:
arr_list = np.array([10, 20, 30, 40, 50])

arr_zeros = np.zeros((3, 3))    # создание матрицы 3х3 со значениями 0

arr_range = np.arange(10)       # создания массива с цифрами от 0 до 9

print("Массив из списка:", arr_list)
print("\nМассив из нулей:\n", arr_zeros)
print("\nМассив из диапозона чисел: ", arr_range)

Массив из списка: [10 20 30 40 50]

Массив из нулей:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Массив из диапозона чисел:  [0 1 2 3 4 5 6 7 8 9]


### Демонстрация атрибутов массива

In [45]:
print("Форма массива (shape):", arr_zeros.shape)
print("Тип данных:          ", arr_zeros.dtype)

Форма массива (shape): (3, 3)
Тип данных:           float64


### Примеры индексирования и срезов

In [46]:
element = arr_range[4]
sub_array = arr_range[3:6]  # получим эелменты с 3 по 6 не включая

print("Элмент с индексом 4:              ", element)
print("Срез массива (элементы с 3 по 6): ", sub_array)

Элмент с индексом 4:               4
Срез массива (элементы с 3 по 6):  [3 4 5]


### Примеры векторных операций и базовых статистик

In [47]:
arr_mult = arr_list * 2         # умножаем каждый элемент массива на 2
arr_mean = np.mean(arr_list)    # считаем среднее значение

print("Массив умноженный на 2:", arr_mult)
print("Среднее значение:      ", arr_mean)

Массив умноженный на 2: [ 20  40  60  80 100]
Среднее значение:       30.0
